const HTTPCONFIG = {
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,

  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

const CUSTOMCONFIG = {
  DUPLICATE_KEY: "Already Exists",
};

export { HTTPCONFIG, CUSTOMCONFIG };
